Repository mauro-codes/uade-gym-api, pull requests merged in 2020-07, with the labels that each got.

#20 Create employee endpoint
  documentation/employee.yaml
  src/components/commons/persona/persona.model.js
  src/components/employee/employee.controller.js
  src/components/employee/employee.model.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
  src/server-init.js
Labels: feature

#21 4 update employee
  documentation/employee.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
  src/server-init.js
Labels: feature

#23 6 get all employees
  documentation/employee.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
Labels: feature

#24 5 delete employee
  documentation/employee.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
Labels: feature

#25 13 post member
  documentation/member.yaml
  src/components/member/medicalInformation.model.js
  src/components/member/member.controller.js
  src/components/member/member.model.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
  src/server-init.js
Labels: feature

#26 Get all members endpoint
  documentation/member.yaml
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
Labels: feature

#28 18 add medical info
  documentation/member.yaml
  src/components/member/medicalInformation.model.js
  src/components/member/member.controller.js
  src/components/member/member.model.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
Labels: feature

#27 17 get member by
  documentation/member.yaml
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
Labels: feature

#30 15 delete member by
  documentation/member.yaml
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
Labels: feature

#31 14 update member by id
  documentation/member.yaml
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
Labels: feature

#34 33 bug missing employee phone
  src/app.js
  src/components/employee/employee.service.js
Labels: bug

#37 Retrieve email on getall
  src/components/member/member.service.js
Labels: bug

#29 1 post activity
  documentation/activity.yaml
  src/components/activity/activity.controller.js
  src/components/activity/activity.model.js
  src/components/activity/activity.routes.js
  src/components/activity/activity.service.js
  src/server-init.js
Labels: feature

#35 12 account new model
  documentation/account.yaml
  src/components/account/account.model.js
  src/components/account/account.service.js
Labels: enhancement

#32 11 get activity by id
  documentation/activity.yaml
  src/components/activity/activity.controller.js
  src/components/activity/activity.routes.js
  src/components/activity/activity.service.js
Labels: feature

#51 42 create plan
  documentation/plan.yaml
  src/components/plan/plan-frecuency.js
  src/components/plan/plan.controller.js
  src/components/plan/plan.model.js
  src/components/plan/plan.routes.js
  src/components/plan/plan.service.js
  src/server-init.js
Labels: feature

#53 10 get all activities
  documentation/activity.yaml
  src/components/activity/activity.controller.js
  src/components/activity/activity.routes.js
  src/components/activity/activity.service.js
Labels: feature

#52 46 member plan
  documentation/member.yaml
  src/components/member/member.controller.js
  src/components/member/member.model.js
  src/components/member/member.routes.js
  src/components/member/member.service.js
Labels: feature

#54 8 update activity - read description please
  documentation/activity.yaml
  src/components/activity/activity.controller.js
  src/components/activity/activity.routes.js
  src/components/activity/activity.service.js
Labels: feature

#56 43 get all plans
  documentation/plan.yaml
  src/components/plan/plan.controller.js
  src/components/plan/plan.routes.js
  src/components/plan/plan.service.js
Labels: feature

#57 44 update plan by id
  documentation/plan.yaml
  src/components/plan/plan.controller.js
  src/components/plan/plan.routes.js
  src/components/plan/plan.service.js
Labels: feature

#59 38 post remuneration for employee
  documentation/employee.yaml
  documentation/remuneration.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
  src/components/employee/remuneration.model.js
Labels: feature

#61 47 create payment
  documentation/member.yaml
  documentation/payment.yaml
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/components/member/payment/payment.model.js
  src/components/member/payment/payment.service.js
  src/components/plan/plan-frecuency.js
Labels: feature

#58 45 delete by id
  documentation/plan.yaml
  src/components/plan/plan.controller.js
  src/components/plan/plan.routes.js
  src/components/plan/plan.service.js
Labels: feature

#62 39 get all remunerations
  documentation/remuneration.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
  src/components/employee/remuneration.model.js
Labels: feature

#63 48 get all payments
  documentation/payment.yaml
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/components/member/payment/payment.service.js
Labels: feature

#64 40 get remunerations by employee
  documentation/remuneration.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
Labels: feature

#65 41 get remuneration by employee id and remuneration id
  documentation/remuneration.yaml
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
Labels: feature

#70 Remuneration.employeeId rename
  src/components/employee/employee.controller.js
  src/components/employee/employee.service.js
  src/components/employee/remuneration.model.js
Labels: enhancement

#75 member model plan is not required
  src/components/member/member.model.js
Labels: bug

#87 Add CUIT attribute to members
  documentation/member.yaml
  src/components/member/member.model.js
  src/components/member/member.service.js
Labels: bug

#85 legal data stored
  src/gym-legal-data.js
Labels: feature

#84 81 post invoice
  documentation/invoice.yaml
  src/components/member/invoice/invoice.model.js
  src/components/member/invoice/invoice.service.js
  src/components/member/member.controller.js
  src/components/member/member.routes.js
  src/gym-legal-data.js
Labels: feature

#94 80 invoice preview
  documentation/invoice.yaml
  src/components/member/invoice/invoice.model.js
  src/components/member/invoice/invoice.service.js
  src/components/member/member.controller.js
  src/components/member/member.routes.js
Labels: feature

#99 83 get all invoices
  documentation/invoice.yaml
  src/components/member/invoice/invoice.service.js
  src/components/member/member.controller.js
  src/components/member/member.routes.js
Labels: feature

#100 93 get job titles and salary
  .eslintignore
  documentation/employee.yaml
  package-lock.json
  package.json
  src/components/employee/employee.controller.js
  src/components/employee/employee.routes.js
  src/components/employee/employee.service.js
  src/components/employee/job-title.service.js
Labels: feature

#103 Fix heroku CORS issue
  src/server-init.js
Labels: bug

#106 104 get invoice by id
  documentation/invoice.yaml
  src/components/member/invoice/invoice.service.js
  src/components/member/member.controller.js
  src/components/member/member.routes.js
Labels: feature

#110 Fix error handling on external service
  documentation/member.yaml
  src/external-services/creditex.service.js
Labels: bug

#111 92 - employee new properties
  documentation/employee.yaml
  src/components/employee/employee.model.js
  src/components/employee/employee.service.js
Labels: enhancement

#114 Return the member id on getAllInvoices
  src/components/member/invoice/invoice.service.js
Labels: enhancement

#112 101 - new attributes for remunerations
  src/components/employee/remuneration/remuneration-details.js
  src/components/employee/remuneration/remuneration.model.js
  src/components/employee/remuneration/remuneration.service.js
Labels: enhancement

#113 98 - calculate vacation detail
  documentation/employee.yaml
  package-lock.json
  src/components/employee/employee.model.js
  src/components/employee/employee.service.js
  src/components/employee/remuneration/remuneration-details.js
Labels: enhancement
